### ISSUE TITLE
Unnecessary hooking of all processes with UIKit

### ISSUE THREAD

**Issue by ren7995** [nahtedetihw/PopLockAndDropIt#1]
Your filter plist tells the hooking library to inject your library into all processing with UIKit, but this is not needed:

- Status bar is managed by SpringBoard itself, your tweak will work fine just by hooking SpringBoard
- This tweak wouldn't work if it was just injected into apps, anyways: you present on SBIconController, which isn't present inside any app besides SpringBoard

TL;DR: You can just filter SpringBoard

**Comment by ren7995** [comment]
Apologies, somehow autocorrect turned "processes" into "processing" two times

**Comment by nahtedetihw** [comment]
It does work in all apps though. I will give your suggestions a try and see if it still works. Thanks!

**Comment by ren7995** [comment]
Yes, it does work in all apps, but that would most likely be because of the library being loaded into SpringBoard (being loaded into the app itself shouldn't matter)

An easy way to test this would be to use something like Choicy to disable injection into SpringBoard, and seeing if it still works in apps
